FROM hotswapagent/meecrowave
COPY ./target/pingperf.war ${DEPLOYMENT_DIR}
ENV ARCHIVE_NAME pingperf.war
ENV CONTEXT pingperf
ENV JAVA_OPTS="-Dorg.apache.tomcat.util.buf.UDecoder.ALLOW_ENCODED_SLASH=true -Xmx128m"
